
trigger:
  branches:
    include:
      - main
pool: fadi-pool

variables:
  - name: MAVEN_CACHE_FOLDER
    value: $(HOME)/.m2/repository
  - name: MAVEN_OPTS
    value: -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)
  - name: JACOCO_CODECOVERAGE
    value: $(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean verify'
    options: '-Dmaven.test.failure.ignore=true'
    publishJUnitResults: true
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
  displayName: 'Run Maven Build'

# Prepare SonarQube Analysis
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'sonarr'  # Replace with your service connection name
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'my-azure-devops-project_my-azure-devops-project_AZK0yBzzKN4gu2Kgjo-i'
    cliSources: 'src'
    extraProperties: |
      sonar.java.binaries=target/classes
  displayName: 'Prepare SonarQube Analysis'

# Run SonarQube Analysis
- task: SonarQubeAnalyze@5
  displayName: 'Run SonarQube Analysis'

# Publish SonarQube Quality Gate Results
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish SonarQube Quality Gate Result'

# Publish Code Coverage Results (JaCoCo)
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/target/site/jacoco/jacoco.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/target/site/jacoco'
    failIfCoverageEmpty: true
  displayName: 'Publish JaCoCo Code Coverage Report'